version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: api-solid-pg
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: